
```{r echo=FALSE}
ipca_indice = 
  '/t/1737/n1/all/v/2266/p/all/d/v2266%2013' %>%
  get_sidra(api=.) %>%
  mutate(date = ymd(paste0(`Mês (Código)`, '01'))) %>%
  dplyr::select(date, Valor) %>%
  mutate(mensal = round((Valor/lag(Valor, 1)-1)*100, 2),
         anual = round((Valor/lag(Valor, 12)-1)*100, 2))


```
```{r echo=FALSE}
## Criar amostra
ipca_subamostra = ipca_indice %>%
  filter(date >= as.Date('2007-06-01'))
```

## Inflação

```{r echo=FALSE}
ipca_subamostra %>%
  tail() %>%
  kable(digits=2)

```

## Inflação Mensal (IPCA)

```{r echo=FALSE}

ggplot(data=ipca_subamostra, aes(x=date, y=mensal))+
  geom_line(size=.8, colour='darkblue')+
  geom_hline(yintercept = 0, colour='red', linetype='dashed')+
  labs(title='Inflação mensal medida pelo IPCA')+
  xlab('')+ylab('% a.m.')+
  scale_x_date(breaks = date_breaks("1 year"),
               labels = date_format("%Y"))+
  theme(axis.text.x=element_text(angle=45, hjust=1),
        panel.background = element_rect(fill='white', colour='white'))

```

## Análise estatística

```{r echo=FALSE}

ipca_subamostra %>%
  mutate(date = yearmonth(date)) %>%
  as_tsibble(index=date) %>%
  gg_subseries(mensal)+
  labs(x='', y='')

```

```{r echo=FALSE}
nucleos = get_series(series, start_date = '2006-07-01') %>%
  purrr::reduce(inner_join)

nucleos_12m <- nucleos %>%
  mutate(across(!date, (function(x) 1+x/100))) %>%
  mutate(across(!date, (function(x) (roll_prod(x, n=12, align='right', 
                                               fill = NA)-1)*100 )))

data_nucleos_12 = nucleos_12m %>%
  filter(date >= as.Date('2007-06-01'))

```

## Inflação e Núcleo

```{r, results='markup'}

## Inflação vs. Núcleos

meta = c(rep(4.5, 139), rep(4.25, 12),
         rep(4, 12), rep(3.75, 12), rep(3.5, 12), rep(3.25, 12))
meta_max = c(rep(4.5+2, 115), meta[-(1:115)]+1.5)
meta_min = c(rep(4.5-2, 115), meta[-(1:115)]-1.5)

metas = tibble(lim_sup=meta_max, meta=meta, 
                lim_inf=meta_min)

media.nucleos <- rowMeans(dplyr::select(data_nucleos_12, -date))

df = tibble(nucleos = round(media.nucleos, 2),
            lim_sup = head(metas$lim_sup, n = nrow(ipca_subamostra)),
            meta = head(metas$meta, n = nrow(ipca_subamostra)),
            lim_inf = head(metas$lim_inf, n = nrow(ipca_subamostra)),
            inflacao = ipca_subamostra$anual,
            date = data_nucleos_12$date)
 
```

```{r, results='markup'}

df %>%
  inner_join(ipca_subamostra, by='date') %>%
  select(date, everything(), -Valor, -inflacao) %>%
  tail() %>%
  kable(digits = 2)

```

## Núcleos de Inflação

```{r echo=FALSE}
ggplot(df, aes(x=date, y=inflacao))+
  geom_ribbon(aes(ymin=lim_inf, ymax=lim_sup), 
              colour='grey70', alpha=0.3)+
  geom_line(aes(y=inflacao, colour='Inflação 12 meses'), size=.8)+
  geom_line(aes(y=meta, colour='Meta de Inflação'), size=.8)+
  geom_line(aes(y=nucleos, colour='Média dos 7 Núcleos'), size=.8)+
  scale_colour_manual('', 
                      values=c('Inflação 12 meses'='darkblue',
                               'Meta de Inflação'='red',
                               'Média dos 7 Núcleos'='black'))+
  theme(legend.position = 'top')+
  scale_x_date(breaks = date_breaks("1 years"),
               labels = date_format("%Y"))+
  xlab('')+ylab('% a.a.')+
  labs(title='Comportamento da Inflação no Brasil',
       caption='Fonte: bcb.gov.br(BCB).')+
  theme(panel.background = element_rect(fill='white',
                                        colour='white'),
        axis.line = element_line(colour='black',
                                 linetype = 'dashed'),
        axis.line.x.bottom = element_line(colour='black'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(.2,.8),
        legend.key.size = unit(.2, "cm"),
        plot.margin=margin(5,5,15,5))+
  geom_label_repel(label=round(tail(df$inflacao, 1) ,2),
                   nudge_y = 2,
                   nudge_x = -2,
                   data = tail(df, 1),
                   color = 'black',
                   fill = 'lightblue')
```

## Núcleos de Inflação

```{r echo=FALSE}

## Gráfico Núcleos

nucleos_data_2 = cbind(data_nucleos_12, 
                       head(metas, n = nrow(data_nucleos_12)))
  
filter(nucleos_data_2, date > '2015-01-01') %>%
ggplot(aes(x=date))+
  geom_ribbon(aes(ymin=lim_inf, ymax=lim_sup), 
              colour='grey', alpha=0.3)+
  geom_line(aes(y=meta, colour='Meta', linetype='Meta'), size=.8)+
  geom_line(aes(y=ipca_ex2, colour='IPCA-EX2', linetype='IPCA-EX2'),
            size=.8)+
  geom_line(aes(y=ipca_ex3, colour='IPCA-EX3', linetype='IPCA-EX3'),
            size=.8)+
  geom_line(aes(y=ipca_ex0, colour='IPCA-EX0', linetype='IPCA-EX0'),
            size=.8)+
  geom_line(aes(y=ipca_ex1, colour='IPCA-EX1', linetype='IPCA-EX1'),
            size=.8)+
  geom_line(aes(y=ipca_ms, colour='IPCA-MS', linetype='IPCA-MS'),
            size=.8)+
  geom_line(aes(y=ipca_ma, colour='IPCA-MA', linetype='IPCA-MA'),
            size=.8)+
  geom_line(aes(y=ipca_dp, colour='IPCA-DP', linetype='IPCA-DP'),
            size=.8)+
  scale_colour_manual(NULL, 
                      values=c('Meta'='darkblue',
                               'IPCA-EX2'='red',
                               'IPCA-EX3'='black',
                               'IPCA-EX0'='orange',
                               'IPCA-EX1'='blue',
                               'IPCA-MS'='#91b8bd',
                               'IPCA-MA'='#8abbd0',
                               'IPCA-DP'='#9ae5de'))+
  scale_linetype_manual(NULL, 
                        values=c('Meta'='solid',
                               'IPCA-EX2'='solid',
                               'IPCA-EX3'='solid',
                               'IPCA-EX0'='solid',
                               'IPCA-EX1'='solid',
                               'IPCA-MS'='solid',
                               'IPCA-MA'='solid',
                               'IPCA-DP'='solid'))+
  theme(legend.position = 'top')+
  scale_x_date(breaks = date_breaks("1 years"),
               labels = date_format("%Y"))+
  xlab('')+ylab('% a.a.')+
  labs(title='Núcleos e Meta de Inflação',
       caption='Fonte: bcb.gov.br(BCB).')+
  theme(panel.background = element_rect(fill='white',
                                        colour='white'),
        axis.line = element_line(colour='black',
                                 linetype = 'dashed'),
        axis.line.x.bottom = element_line(colour='black'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(.85,.9),
        legend.key.size = unit(0.3, "cm"),
        plot.margin=margin(5,5,15,5))

```

## Núcleos de Inflação

```{r}
nucleos_12m %>%
  gather(variavel, valor, -date) %>%
  ggplot(aes(x=date, y=valor, colour=variavel))+
  geom_line(size=.8)+
  facet_wrap(~variavel, scales='free')+
  theme(legend.position = 'none')+
  labs(x='', y='')
```

## Classificações IPCA

```{r echo=FALSE}
classificacoes_ipca = get_series(series2, start_date = '2007-01-01') %>%
  purrr::reduce(inner_join)

classificacoes_ipca %>%
  gather(variavel, valor, -date) %>%
  ggplot(aes(x=date, y=valor, colour=variavel))+
  geom_line()+
  facet_wrap(~variavel, scales='free')+
  theme(legend.position = 'none')+
  labs(x='', y='')
```
```{r echo=FALSE}
classificacoes_ipca_12m = 
  classificacoes_ipca[,-1] %>%
  ts(start=c(2007,01), freq=12) %>%
  acum_p(12) %>%
  as_tibble() %>%
  mutate(date = classificacoes_ipca$date) %>%
  select(date, everything()) %>%
  drop_na()

```

## Classificações do IPCA (acum.12 meses)

```{r}

classificacoes_ipca_12m %>%
  gather(variavel, valor, -date) %>%
  ggplot(aes(x=date, y=valor, colour=variavel))+
  geom_line(size=.8)+
  facet_wrap(~variavel, scales='free')+
  theme(legend.position = 'none')+
  labs(x='', y='')
```

